### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by catfoolyou** [wxnnvs/AutoEagler#10]
I'm unable to connect to the server with the browser or offline versions of 1.8. I have all of the jars downloaded and correctly pointed to in the python files. 
The desktop runtime does not work as well. 

The server lists the port to be 25577 instead of 8081, but it will not work on either port.

The following message is printed in the console when I try to connect to `ws://localhost:25577` (nothing happens when I use port 8081)

![Screenshot 2024-01-08 121704](https://github.com/wxnnvs/AutoEagler/assets/95507639/8f4f721e-c108-487c-9ae8-ba9745371914)

**Comment by wxnnvs** [comment]
let me look into it

**Comment by wxnnvs** [comment]
I see u are using the eaglercraft desktop runtime
that is 1.5.2 only
if you install 1.5.2 in AutoEagler it should work

**Comment by leahanderson1** [comment]
> I see u are using the eaglercraft desktop runtime that is 1.5.2 only if you install 1.5.2 in AutoEagler it should work

kid named https://github.com/radmanplays/EaglerDesktopRuntime

**Comment by wxnnvs** [comment]
> > I see u are using the eaglercraft desktop runtime that is 1.5.2 only if you install 1.5.2 in AutoEagler it should work


Is it 1.8 also? My bad bro

**Comment by wxnnvs** [comment]
> kid named https://github.com/radmanplays/EaglerDesktopRuntime
> 

Is it 1.8 also? My bad

**Comment by catfoolyou** [comment]
I'm using the 1.8.8u19 runtime

**Comment by catfoolyou** [comment]
I saw some text about being unable to install programs in the console, maybe its because im using a school laptop.

**Comment by wxnnvs** [comment]
> I saw some text about being unable to install programs in the console, maybe its because im using a school laptop.

That could be a problem yes

**Comment by wxnnvs** [comment]
Can u try connecting to ws://localhost without :8081

**Comment by catfoolyou** [comment]
> kid named https://github.com/radmanplays/EaglerDesktopRuntime

I'm using this: https://github.com/catfoolyou/EaglercraftX-Desktop-Runtime (its slightly modified)

**Comment by catfoolyou** [comment]
Connecting to ws://localhost didnt help

**Comment by catfoolyou** [comment]
I got it working on my personal Windows pc. Runs on ws://localhost:8081 as expected

**Comment by wxnnvs** [comment]
> I got it working on my personal Windows pc. Runs on ws://localhost:8081 as expected

Perfect, have fun!
