### ISSUE TITLE
How to deploy to Cyclic

### ISSUE THREAD

**Issue by Arsenaloro** [wxnnvs/AutoEagler#11]
Hello.
I have found a a hosting for eaglercraft. So yeah how do i deploy to Cyclic, when i do it it says specify package.json please help

**Comment by catfoolyou** [comment]
Not sure if its gonna work, cause it needs python. Try using gitpod instead (open this repo, install python and follow install instructions), though it might not work because gitpod is a unix/linux environment (I think).

**Comment by Arsenaloro** [comment]
Yup, cyclic is actually supporting python

**Comment by Arsenaloro** [comment]
you just have to go in advanced options when your deploying.

**Comment by wxnnvs** [comment]
can you have a cyclic host with both python and java installed? @Arsenaloro

**Comment by wxnnvs** [comment]
also what site dou you mean because cyclic.sh is javascript only

**Comment by Arsenaloro** [comment]
yeah cyclic.sh, it has a python now compability.
![image](https://github.com/wxnnvs/AutoEagler/assets/125985450/271086b5-a125-4e64-8f21-32193d6a6c3a)
like i tried to use the github from it, and i didnt try installing java but i think it should.

**Comment by Arsenaloro** [comment]
Also when importing the project it says something like it needs a .json file

**Comment by Arsenaloro** [comment]
Also does this actually support linux? @wxnnvs

**Comment by wxnnvs** [comment]
> yeah cyclic.sh, it has a python now compability.
> ![image](https://github.com/wxnnvs/AutoEagler/assets/125985450/271086b5-a125-4e64-8f21-32193d6a6c3a)
> like i tried to use the github from it, and i didnt try installing java but i think it should.

If you don't try, you shouldn't ask here
Go get support for cyclic on their page

If you can install java, python and ngrok, it should work

**Comment by wxnnvs** [comment]
> Also does this actually support linux? @wxnnvs
> 

Look at readme

**Comment by Arsenaloro** [comment]
Its just an orange emoji
