### ISSUE TITLE
CMD python error

### ISSUE THREAD

**Issue by JMcrafter26** [wxnnvs/AutoEagler#12]
Some (the most) windows computers do not recognize python3. Instead use just python:

```batch
@echo off
title "Checking software ..."

set python=python3
where %python% >nul 2>nul
if %errorlevel%==1 (
    set python=python
    where %python% >nul 2>nul
    if %errorlevel%==1 (
        @echo Python not found, please install Python 3 from https://python.org
        pause
        exit 0
    )
)

where java >nul 2>nul
if %errorlevel%==1 (
    @echo Java not found, please install Java 8 from https://java.com
    pause
    exit 0
)

%python% -m pip install -r requirements.txt

title "Running ..."

%python% autoeagler.py

echo Script exited.

timeout 5
```

**Comment by wxnnvs** [comment]
if you set `%python%` to python3 it'll result in the same thing
Also if you install python properly you **will** have the `python3` command

**Comment by wxnnvs** [comment]
for proof
```
@echo off
set python=python3
where %python%
pause
```
results in:
```
C:\Path\To\Python\python3.exe
```

**Comment by wxnnvs** [comment]
oh my bad, its a double check

**Comment by JMcrafter26** [comment]
Or you could just use `py` like in this post, which is easier and better

https://stackoverflow.com/a/41492852/17158847

**Comment by JMcrafter26** [comment]
BTW, since when did ngrok require authentication?

**Comment by wxnnvs** [comment]
> Or you could just use `py` like in this post, which is easier and better
> 
> https://stackoverflow.com/a/41492852/17158847

I'll update it to python later on
Currently busy

**Comment by wxnnvs** [comment]
> BTW, since when did ngrok require authentication?

Idk but it sucks
