### ISSUE TITLE
Is it possible to run through codespaces? 

### ISSUE THREAD

**Issue by STPv22** [wxnnvs/AutoEagler#16]
I tried it, but when I tried to join, it said connection reset by peer, and spigot would have a seizure.

I installed openJDK, and ran the files with java -jar

**Comment by STPv22** [comment]
``` bash
java -jar filename
```
testing if this works

**Comment by wxnnvs** [comment]
if configured properly it should work

**Comment by STPv22** [comment]
more info?

**Comment by wxnnvs** [comment]
if the right java version is installed and you run the commands manually, it should work 
the python file will *not* work as it is windows only
