### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Bungee-1.8.8' Script exited.

### ISSUE THREAD

**Issue by ethan1324567** [wxnnvs/AutoEagler#20]
Hello, today I tried running this script on my linux system, chose option 3, and after I chose my region, it threw this error:
Traceback (most recent call last):
  File "/home/ubuntu/AutoEagler-2.3.3/autoeagler.py", line 436, in <module>
    main()
  File "/home/ubuntu/AutoEagler-2.3.3/autoeagler.py", line 409, in main
    ngrok_start(version)
  File "/home/ubuntu/AutoEagler-2.3.3/autoeagler.py", line 206, in ngrok_start
    run_servers(server_version)
  File "/home/ubuntu/AutoEagler-2.3.3/autoeagler.py", line 149, in run_servers
    os.chdir(os.path.dirname(bungee_location_1_8_8))
FileNotFoundError: [Errno 2] No such file or directory: 'Bungee-1.8.8'
Script exited.

**Comment by wxnnvs** [comment]
Did you setup AutEagler before running it with ngrok?
Try using option 1 before any other

**Comment by ethan1324567** [comment]
Sorry, I didn't catch that I had to run that before it.
Now I get this error after running option 1, entering my NGROK authtoken, selecting version 1.8.8, survival mode, disabling hardcore, and generating a random seed even though I am using the default Ubuntu Server terminal:
No suitable terminal emulator found. Please run the command manually.
No suitable terminal emulator found. Please run the command manually.
Servers starting ...
Stopping servers...
servers stopped
Enabling EULA in spigot...
Traceback (most recent call last):
  File "/home/ubuntu/AutoEagler/autoeagler.py", line 436, in <module>
    main()
  File "/home/ubuntu/AutoEagler/autoeagler.py", line 336, in main
    replace_in_file("Server-1.8.8/eula.txt", "false", "true")  # Change eula to                                                                                                              true
  File "/home/ubuntu/AutoEagler/autoeagler.py", line 81, in replace_in_file
    with open(file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'Server-1.8.8/eula.txt'
Script exited.

**Comment by STPv22** [comment]
Because you are running on Linux, It can't open up windows to run the servers on. To run type in the folder of the jar `java -jar filename`

**Comment by ethan1324567** [comment]
That works, but isn't a fix because it doesn't save the configurations chosen in the previous steps

**Comment by wxnnvs** [comment]
@ethan1324567 this is windows only for now
My bad, I should've asked your OS

There will be a docker release sometime in the future with Linux support

**Comment by ethan1324567** [comment]
Ok, but then why is there a start.sh file?

**Comment by STPv22** [comment]
You can use AutoEagler to set up your server, but not to run the server on linux.

**Comment by leahanderson1** [comment]
womp womp if using linux you probably know how to do it yourself

**Comment by STPv22** [comment]
I agree

**Comment by wxnnvs** [comment]
> Ok, but then why is there a start.sh file?

As said, linux support is *in development*
And as otter said you can use the script to set everything up, but running it is your own problem.

**Comment by ethan1324567** [comment]
alr, looking forward to the linux release
