### ISSUE TITLE
How would I make the server IP not randomly generated?

### ISSUE THREAD

**Issue by stpv221** [wxnnvs/AutoEagler#21]
How would I change the endpoint to be my domain in ngrok? also, how would I make the physical WebSocket?

**Comment by wxnnvs** [comment]
Adding your domain should be possible from within the ngrok dashboard, but you might have to purchase premium for it

**Comment by wxnnvs** [comment]
What do you mean by physical websocket?

**Comment by stpv221** [comment]
I mean upgrading it. Making it so that it displays an HTML file instead of 404.

**Comment by stpv221** [comment]
> Adding your domain should be possible from within the ngrok dashboard, but you might have to purchase premium for it

How would I do that from a registered domain, without ngrok?

**Comment by stpv221** [comment]
oh i guess i figured out upgrading the WebSocket... I enable it in the bungee, right?

**Comment by stpv221** [comment]
I just want the endpoint domain to be static

**Comment by wxnnvs** [comment]
> I just want the endpoint domain to be static

You would have to configure this through ngrok premium
I might add caddy reverse proxy wich would allow you to connect a domain

**Comment by stpv221** [comment]
ok
