### ISSUE TITLE
Python Not Found

### ISSUE THREAD

**Issue by purplesgamestash** [wxnnvs/AutoEagler#5]
When trying to use AutoEagler with the latest version of python installed, it says "Python Not Found, please install Python 3 from https://python.org". python.exe is added to PATH, and Python is disabled under Manage app extension aliases.

**Comment by leahanderson1** [comment]
can you run the python interpreter in powershell?

**Comment by purplesgamestash** [comment]
no, it gives this error:
Program 'python.exe' failed to run: The system cannot find the file specifiedAt line:1 char:1
+ python
+ ~~~~~~.
At line:1 char:1
+ python
+ ~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
sorry if I'm asking a stupid question btw, I'm very new to python

**Comment by leahanderson1** [comment]
remove python from your PATH, and install it from the microsoft store instead

**Comment by purplesgamestash** [comment]
what is it called in PATH?

**Comment by leahanderson1** [comment]
how did you install python?

**Comment by purplesgamestash** [comment]
through python.org

**Comment by purplesgamestash** [comment]
and i checked the box "add python to PATH"

**Comment by wxnnvs** [comment]
> and i checked the box "add python to PATH" 

Delete python
Reinstall python

If the issue persists, try installing from the ms store as @OtterCodes101 said

**Comment by purplesgamestash** [comment]
Fixed! Thanks
